# Generated by Django 4.2.16 on 2025-12-13 08:54

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iss', '0007_codcor_alter_worker_cod_cor_worker_cod_cor_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoFinMonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)])),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('hours_worked', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ore lucrate în luna respectivă', max_digits=8)),
                ('salary_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost salarial total din Excel', max_digits=12)),
                ('tarif_orar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tarif orar (copiat din Client)', max_digits=10)),
                ('cost_cazare', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost cazare (copiat din Client)', max_digits=10)),
                ('cost_masa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost masă (copiat din Client)', max_digits=10)),
                ('cost_transport', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost transport (copiat din Client)', max_digits=10)),
                ('cost_concediu', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost concediu (din setări globale)', max_digits=10)),
                ('cheltuieli_indirecte', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cheltuieli indirecte alocate (din setări globale)', max_digits=10)),
                ('profit_brut', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Profit brut calculat', max_digits=12)),
                ('is_validated', models.BooleanField(default=False, help_text='True = dataset validat și înghețat')),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Observații (ex: ore împărțite între 2 clienți)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecofin_reports', to='iss.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecofin_reports_created', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecofin_validated', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecofin_reports', to='iss.worker')),
            ],
            options={
                'verbose_name': 'Raport Eco-Fin',
                'verbose_name_plural': 'Rapoarte Eco-Fin',
                'ordering': ['-year', '-month', 'worker__nume'],
            },
        ),
        migrations.CreateModel(
            name='EcoFinImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('filename', models.CharField(max_length=255)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('successful_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'În așteptare'), ('processing', 'În procesare'), ('preview', 'Preview'), ('validated', 'Validat'), ('failed', 'Eșuat')], default='pending', max_length=20)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecofin_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import Eco-Fin',
                'verbose_name_plural': 'Importuri Eco-Fin',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EcoFinSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Anul pentru care se aplică setările', validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)])),
                ('month', models.PositiveIntegerField(help_text='Luna pentru care se aplică setările (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('cheltuieli_indirecte', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cheltuieli indirecte lunare (se împart la nr. lucrători)', max_digits=10)),
                ('cost_concediu', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost concediu per lucrător', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecofin_settings_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Setare Eco-Fin',
                'verbose_name_plural': 'Setări Eco-Fin',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]

