# Generated by Django 4.2.16 on 2025-12-21 10:18

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iss', '0011_ambasada_worker_ambasada'),
        ('ecofin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecofinmonthlyreport',
            options={'ordering': ['-year', '-month', 'worker__nume'], 'verbose_name': '[Depreciat] Raport Eco-Fin', 'verbose_name_plural': '[Depreciat] Rapoarte Eco-Fin'},
        ),
        migrations.RemoveField(
            model_name='ecofinimportbatch',
            name='failed_rows',
        ),
        migrations.RemoveField(
            model_name='ecofinimportbatch',
            name='successful_rows',
        ),
        migrations.AddField(
            model_name='ecofinimportbatch',
            name='error_rows',
            field=models.PositiveIntegerField(default=0, help_text='Rânduri cu erori'),
        ),
        migrations.AddField(
            model_name='ecofinimportbatch',
            name='file',
            field=models.FileField(blank=True, help_text='Fișierul Excel original', null=True, upload_to='ecofin/imports/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='ecofinimportbatch',
            name='matched_rows',
            field=models.PositiveIntegerField(default=0, help_text='Rânduri cu lucrător identificat'),
        ),
        migrations.AddField(
            model_name='ecofinimportbatch',
            name='processed_rows',
            field=models.PositiveIntegerField(default=0, help_text='Rânduri procesate în înregistrări'),
        ),
        migrations.AddField(
            model_name='ecofinimportbatch',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ecofinimportbatch',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecofin_imports_validated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ecofinsettings',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='True = luna validată, setările nu mai pot fi modificate'),
        ),
        migrations.AlterField(
            model_name='ecofinimportbatch',
            name='status',
            field=models.CharField(choices=[('pending', 'În așteptare'), ('processing', 'În procesare'), ('preview', 'Preview (așteptare validare)'), ('validated', 'Validat și procesat'), ('failed', 'Eșuat'), ('cancelled', 'Anulat')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ecofinmonthlyreport',
            name='cheltuieli_indirecte',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='ecofinmonthlyreport',
            name='cost_cazare',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='ecofinmonthlyreport',
            name='cost_concediu',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='ecofinmonthlyreport',
            name='cost_masa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='ecofinmonthlyreport',
            name='cost_transport',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='ecofinmonthlyreport',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='ecofinmonthlyreport',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ecofinmonthlyreport',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ecofinmonthlyreport',
            name='profit_brut',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='ecofinmonthlyreport',
            name='salary_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='ecofinmonthlyreport',
            name='tarif_orar',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='ecofinsettings',
            name='cheltuieli_indirecte',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cheltuieli indirecte lunare totale (se împart la nr. lucrători activi)', max_digits=12),
        ),
        migrations.CreateModel(
            name='EcoFinImportedRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(help_text='Numărul rândului din Excel')),
                ('nr_cim', models.CharField(help_text='Număr CIM din Excel', max_length=50)),
                ('nume', models.CharField(blank=True, help_text='Nume din Excel', max_length=100)),
                ('prenume', models.CharField(blank=True, help_text='Prenume din Excel', max_length=100)),
                ('salariu_brut', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Salariu brut din Excel', max_digits=12)),
                ('ore_lucrate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ore lucrate din Excel', max_digits=8)),
                ('brut1', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Brut1 din Excel', max_digits=12)),
                ('net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Salariu net din Excel', max_digits=12)),
                ('retineri', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rețineri din Excel', max_digits=12)),
                ('rest_plata', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rest de plată din Excel', max_digits=12)),
                ('cam', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Contribuție asigurări muncă (CAM) din Excel', max_digits=12)),
                ('status', models.CharField(choices=[('raw', 'Brut (neprocesat)'), ('matched', 'Identificat'), ('error', 'Eroare identificare'), ('processed', 'Procesat')], default='raw', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Mesaj eroare la identificare')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='ecofin.ecofinimportbatch')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecofin_imported_rows', to='iss.client')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecofin_imported_rows', to='iss.worker')),
            ],
            options={
                'verbose_name': 'Rând Importat Eco-Fin',
                'verbose_name_plural': 'Rânduri Importate Eco-Fin',
                'ordering': ['batch', 'row_number'],
            },
        ),
        migrations.CreateModel(
            name='EcoFinProcessedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)])),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('nr_cim', models.CharField(help_text='Nr CIM la momentul procesării', max_length=50)),
                ('ore_lucrate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ore lucrate în luna respectivă', max_digits=8)),
                ('salariu_brut', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Salariu brut din Excel', max_digits=12)),
                ('cam', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Contribuție asigurări muncă (CAM)', max_digits=12)),
                ('net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Salariu net', max_digits=12)),
                ('retineri', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rețineri', max_digits=12)),
                ('rest_plata', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rest de plată', max_digits=12)),
                ('cost_salarial_complet', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost salarial complet = salariu_brut + cam', max_digits=12)),
                ('tarif_orar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tarif orar (copiat din Client)', max_digits=10)),
                ('cost_cazare', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost cazare lunar (copiat din Client)', max_digits=10)),
                ('cost_masa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost masă lunar (copiat din Client)', max_digits=10)),
                ('cost_transport', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost transport lunar (copiat din Client)', max_digits=10)),
                ('cota_indirecte', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cota cheltuieli indirecte = total_indirecte / nr_salariati', max_digits=10)),
                ('cost_concediu', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost concediu per lucrător (din setări globale)', max_digits=10)),
                ('cost_salariat_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost total = salarial_complet + cazare + masa + transport + indirecte + concediu', max_digits=12)),
                ('venit_generat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Venit = ore_lucrate × tarif_orar', max_digits=12)),
                ('profitabilitate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Profitabilitate = venit_generat - cost_salariat_total', max_digits=12)),
                ('is_validated', models.BooleanField(default=False, help_text='True = înregistrare validată și înghețată')),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Observații')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecofin_processed_records', to='iss.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecofin_records_created', to=settings.AUTH_USER_MODEL)),
                ('imported_row', models.OneToOneField(blank=True, help_text='Legătură la rândul importat original', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processed_record', to='ecofin.ecofinimportedrow')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecofin_validated_records', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecofin_processed_records', to='iss.worker')),
            ],
            options={
                'verbose_name': 'Înregistrare Procesată Eco-Fin',
                'verbose_name_plural': 'Înregistrări Procesate Eco-Fin',
                'ordering': ['-year', '-month', 'worker__nume'],
                'unique_together': {('worker', 'client', 'year', 'month')},
            },
        ),
    ]

