# Generated by Django 4.2.16 on 2025-12-02 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(max_length=255)),
                ('tara', models.CharField(blank=True, max_length=50)),
                ('oras', models.CharField(blank=True, max_length=50)),
                ('judet', models.CharField(blank=True, max_length=50)),
                ('adresa', models.CharField(blank=True, max_length=255)),
                ('cod_fiscal', models.CharField(blank=True, max_length=50)),
                ('tarif_orar', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nr_ore_minim', models.IntegerField(default=0)),
                ('cazare_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('masa_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transport_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50)),
                ('prenume', models.CharField(max_length=50)),
                ('cetatenie', models.CharField(blank=True, max_length=50)),
                ('stare_civila', models.CharField(blank=True, choices=[('M', 'M'), ('NM', 'NM')], max_length=2)),
                ('copii_intretinere', models.SmallIntegerField(default=0)),
                ('sex', models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('data_nasterii', models.DateField(blank=True, null=True)),
                ('pasaport_nr', models.CharField(max_length=20, unique=True)),
                ('data_emitere_pass', models.DateField(blank=True, null=True)),
                ('data_exp_pass', models.DateField(blank=True, null=True)),
                ('oras_domiciliu', models.CharField(blank=True, max_length=100)),
                ('data_introducere', models.DateTimeField(auto_now_add=True)),
                ('cod_cor', models.CharField(blank=True, max_length=10)),
                ('dosar_wp_nr', models.CharField(blank=True, max_length=50)),
                ('data_solicitare_wp', models.DateField(blank=True, null=True)),
                ('data_programare_wp', models.DateField(blank=True, null=True)),
                ('judet_wp', models.CharField(blank=True, max_length=50)),
                ('data_solicitare_viza', models.DateField(blank=True, null=True)),
                ('data_programare_interviu', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Aviz solicitat', 'Aviz solicitat'), ('Aviz emis', 'Aviz emis'), ('Viza solicitata', 'Viza solicitată'), ('Viza obtinuta', 'Viza obținută'), ('Viza respinsa', 'Viza respinsă'), ('Viza redepusa', 'Viza redepusă'), ('Candidat retras', 'Candidat retras'), ('Sosit cu CIM semnat', 'Sosit cu CIM semnat'), ('Permis de sedere solicitat', 'Permis de ședere solicitat'), ('Permis de sedere emis', 'Permis de ședere emis'), ('Activ', 'Activ'), ('Suspendat', 'Suspendat'), ('Inactiv', 'Inactiv')], default='Aviz solicitat', max_length=40)),
                ('data_depunere_ps', models.DateField(blank=True, null=True)),
                ('data_programare_ps', models.DateField(blank=True, null=True)),
                ('cnp', models.CharField(blank=True, max_length=13)),
                ('data_intrare_ro', models.DateField(blank=True, null=True)),
                ('cim_nr', models.CharField(blank=True, max_length=50)),
                ('data_emitere_cim', models.DateField(blank=True, null=True)),
                ('data_emitere_ps', models.DateField(blank=True, null=True)),
                ('data_expirare_ps', models.DateField(blank=True, null=True)),
                ('adresa_ro', models.CharField(blank=True, max_length=255)),
                ('observatii', models.TextField(blank=True)),
                ('folder_doc', models.CharField(blank=True, max_length=255)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers_introdusi', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='iss.client')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Agent', 'Agent'), ('Expert', 'Expert'), ('Management', 'Management'), ('Admin', 'Admin')], default='Agent', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
