# Generated by Django 4.2.16 on 2025-12-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telefon',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
