# Generated by Django 4.2.16 on 2025-12-03 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import iss.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iss', '0002_add_telefon_to_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('pasaport', 'Pașaport'), ('viza', 'Viză'), ('aviz_igi', 'Aviz IGI'), ('cim', 'Contract Individual de Muncă'), ('permis_sedere', 'Permis de Ședere'), ('certificat_medical', 'Certificat Medical'), ('cazier', 'Cazier Judiciar'), ('diploma', 'Diplomă/Certificat Studii'), ('cv', 'CV'), ('foto', 'Fotografie'), ('contract_cazare', 'Contract Cazare'), ('altele', 'Alte Documente')], default='altele', max_length=30)),
                ('file', models.FileField(upload_to=iss.models.worker_document_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='iss.worker')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
