# Generated by Django 4.2.16 on 2025-12-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iss', '0003_add_worker_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='cod_cor',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
