# Generated by Django 4.2.16 on 2025-12-03 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iss', '0004_alter_worker_cod_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='expert',
            field=models.ForeignKey(blank=True, help_text='Expert/Manager care primește notificările pentru acest lucrător', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers_asignati', to=settings.AUTH_USER_MODEL),
        ),
    ]
