# Generated by Django 4.2.16 on 2025-12-03 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iss', '0005_worker_expert'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('SYSTEM', 'Sistem'), ('AUTH', 'Autentificare'), ('ACTIVITY', 'Activitate')], db_index=True, default='ACTIVITY', max_length=20)),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login eșuat'), ('CREATE', 'Creare'), ('UPDATE', 'Modificare'), ('DELETE', 'Ștergere'), ('STATUS_CHANGE', 'Schimbare status'), ('UPLOAD', 'Upload document'), ('DOWNLOAD', 'Download document'), ('BULK_IMPORT', 'Import bulk'), ('EXPORT', 'Export date'), ('ERROR', 'Eroare'), ('WARNING', 'Avertizare'), ('INFO', 'Informație')], db_index=True, max_length=20)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('target_model', models.CharField(blank=True, db_index=True, max_length=50)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_repr', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Activitate',
                'verbose_name_plural': 'Loguri Activitate',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'log_type'], name='iss_activit_timesta_f31feb_idx'), models.Index(fields=['user', '-timestamp'], name='iss_activit_user_id_aef85b_idx'), models.Index(fields=['target_model', 'target_id'], name='iss_activit_target__438c42_idx')],
            },
        ),
    ]
