# Generated by Django 4.2.16 on 2025-12-18 16:39

from django.db import migrations, models
import iss.models


class Migration(migrations.Migration):

    dependencies = [
        ('iss', '0009_templatedocument_generateddocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatedocument',
            name='file',
            field=models.FileField(help_text='Fișier Word (.docx)', upload_to=iss.models.template_document_path),
        ),
    ]

